baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Website Tomi"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/https://github.com/Mhmmdtomi/blok.ku/blob/master/website/static/uploads/picsart_09-13-05-44-14.jpg"
  name: "Muhammad Tomi Ahmadani"
  namecolor: ffc107
  profession: "Student"
  github: "https://github.com"
  linkedin: "https://linkedin.com"
  twitter: "https://twitter.com/"
  instagram: "https://instagram.com/mhmmd_tomi1613"
  facebook: "https://facebook.com"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Tomi"
  descripe_l2_person: "This is my biodata [here](#projects)"
  skills:
    - name: Playing Game
      percentage: 95
    - name: Desain Correl
      percentage: 80
    - name: Playing Badminton
      percentage: 80
    - name: lying around
      percentage: 100

  # Experience
  disable_experience: false
  experience:
    - company: "Google"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Software developer"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Facebook"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "Sd/Mi"
      branch: "Tumpeng"
      university: "Mi Salafiyah Tumpeng"
      startedyear: "2010"
      graduation: "2016"
    - degree: "Smp"
      branch: "Tumpeng"
      university: "Smp Negeri 4 Candipuro"
      startedyear: "2016"
      graduation: "2019"
    - degree: "Sma/Smk"
      branch: "Pasirian"
      university: "Smk Negeri Pasirian"
      startedyear: "2019"
      graduation: "_"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "tomi.rrq165@gmail.com"
  numberphone: 085813078679

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
